/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ResponseStatus = IDL.Variant({
  'LeadsGenerated' : IDL.Null,
  'NoResponse' : IDL.Null,
  'ActiveDiscussion' : IDL.Null,
  'NegativeFeedback' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FacebookOutreachEntry = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Nat,
  'postContent' : IDL.Text,
  'responseStatus' : ResponseStatus,
  'updatedAt' : IDL.Nat,
  'numReactions' : IDL.Nat,
  'datePosted' : IDL.Text,
  'groupUrl' : IDL.Text,
  'numComments' : IDL.Nat,
  'groupName' : IDL.Text,
  'attachment' : IDL.Opt(ExternalBlob),
  'followUpDate' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const HookTemplate = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        ResponseStatus,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [FacebookOutreachEntry],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [FacebookOutreachEntry], ['query']),
  'getFollowUpToday' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FacebookOutreachEntry)],
      ['query'],
    ),
  'getGroupNotes' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getGroupResponseSummary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getHookTemplatesForCaller' : IDL.Func(
      [],
      [IDL.Vec(HookTemplate)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllGroupNotes' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'listEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(FacebookOutreachEntry)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHookTemplates' : IDL.Func([IDL.Vec(HookTemplate)], [], []),
  'setGroupNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        ResponseStatus,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [FacebookOutreachEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ResponseStatus = IDL.Variant({
    'LeadsGenerated' : IDL.Null,
    'NoResponse' : IDL.Null,
    'ActiveDiscussion' : IDL.Null,
    'NegativeFeedback' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FacebookOutreachEntry = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'postContent' : IDL.Text,
    'responseStatus' : ResponseStatus,
    'updatedAt' : IDL.Nat,
    'numReactions' : IDL.Nat,
    'datePosted' : IDL.Text,
    'groupUrl' : IDL.Text,
    'numComments' : IDL.Nat,
    'groupName' : IDL.Text,
    'attachment' : IDL.Opt(ExternalBlob),
    'followUpDate' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const HookTemplate = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          ResponseStatus,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [FacebookOutreachEntry],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [FacebookOutreachEntry], ['query']),
    'getFollowUpToday' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FacebookOutreachEntry)],
        ['query'],
      ),
    'getGroupNotes' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getGroupResponseSummary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getHookTemplatesForCaller' : IDL.Func(
        [],
        [IDL.Vec(HookTemplate)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllGroupNotes' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'listEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(FacebookOutreachEntry)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHookTemplates' : IDL.Func([IDL.Vec(HookTemplate)], [], []),
    'setGroupNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          ResponseStatus,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [FacebookOutreachEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };