/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FacebookOutreachEntry {
  'id' : bigint,
  'createdAt' : bigint,
  'postContent' : string,
  'responseStatus' : ResponseStatus,
  'updatedAt' : bigint,
  'numReactions' : bigint,
  'datePosted' : string,
  'groupUrl' : string,
  'numComments' : bigint,
  'groupName' : string,
  'attachment' : [] | [ExternalBlob],
  'followUpDate' : string,
}
export interface HookTemplate { 'title' : string, 'content' : string }
export type ResponseStatus = { 'LeadsGenerated' : null } |
  { 'NoResponse' : null } |
  { 'ActiveDiscussion' : null } |
  { 'NegativeFeedback' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      ResponseStatus,
      string,
      [] | [ExternalBlob],
    ],
    FacebookOutreachEntry
  >,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[bigint], FacebookOutreachEntry>,
  'getFollowUpToday' : ActorMethod<[string], Array<FacebookOutreachEntry>>,
  'getGroupNotes' : ActorMethod<[string], [] | [string]>,
  'getGroupResponseSummary' : ActorMethod<[], Array<[string, bigint]>>,
  'getHookTemplatesForCaller' : ActorMethod<[], Array<HookTemplate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllGroupNotes' : ActorMethod<[], Array<[string, string]>>,
  'listEntries' : ActorMethod<[bigint, bigint], Array<FacebookOutreachEntry>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHookTemplates' : ActorMethod<[Array<HookTemplate>], undefined>,
  'setGroupNotes' : ActorMethod<[string, string], undefined>,
  'updateEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      ResponseStatus,
      string,
      [] | [ExternalBlob],
    ],
    FacebookOutreachEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];