/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface InquirySummary {
    girlsNightOut: bigint;
    generalDIY: bigint;
    birthdayPartyKids: bigint;
    birthdayPartyAdult: bigint;
    corporateTeamBuilding: bigint;
    fieldTrips: bigint;
    bacheloretteBridalShower: bigint;
}
export interface HookTemplate {
    title: string;
    content: string;
}
export interface FacebookOutreachEntry {
    id: bigint;
    typeOfInterest: TypeOfInterest;
    owner: Principal;
    createdAt: bigint;
    postContent: string;
    responseStatus: ResponseStatus;
    updatedAt: bigint;
    numReactions: bigint;
    datePosted: string;
    groupUrl: string;
    numComments: bigint;
    leadContactInfo: string;
    craftCategory: CraftCategory;
    groupName: string;
    attachment?: ExternalBlob;
    followUpDate: string;
    eventType: EventType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CraftCategory {
    CandleMaking = "CandleMaking",
    SoapMaking = "SoapMaking",
    SplatterRoom = "SplatterRoom"
}
export enum EventType {
    GeneralDIYIndividual = "GeneralDIYIndividual",
    BirthdayPartyKids = "BirthdayPartyKids",
    BirthdayPartyAdult = "BirthdayPartyAdult",
    BacheloretteBridalShower = "BacheloretteBridalShower",
    GirlsNightOut = "GirlsNightOut",
    CorporateTeamBuilding = "CorporateTeamBuilding",
    FieldTrips = "FieldTrips"
}
export enum ResponseStatus {
    LeadsGenerated = "LeadsGenerated",
    NoResponse = "NoResponse",
    ActiveDiscussion = "ActiveDiscussion",
    NegativeFeedback = "NegativeFeedback"
}
export enum TypeOfInterest {
    Availability = "Availability",
    Price = "Price",
    GroupBooking = "GroupBooking"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEntry(groupName: string, groupUrl: string, datePosted: string, postContent: string, numReactions: bigint, numComments: bigint, responseStatus: ResponseStatus, followUpDate: string, craftCategory: CraftCategory, typeOfInterest: TypeOfInterest, eventType: EventType, leadContactInfo: string, attachment: ExternalBlob | null): Promise<FacebookOutreachEntry>;
    deleteEntry(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEntry(id: bigint): Promise<FacebookOutreachEntry>;
    getFollowUpToday(today: string): Promise<Array<FacebookOutreachEntry>>;
    getGroupNotes(groupUrl: string): Promise<string | null>;
    getGroupResponseSummary(): Promise<Array<[string, bigint]>>;
    getHookTemplatesForCaller(): Promise<Array<HookTemplate>>;
    getInquirySummaryByEventType(): Promise<InquirySummary>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    health(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAllGroupNotes(): Promise<Array<[string, string]>>;
    listEntries(page: bigint, pageSize: bigint): Promise<Array<FacebookOutreachEntry>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveHookTemplates(templates: Array<HookTemplate>): Promise<void>;
    setGroupNotes(groupUrl: string, notes: string): Promise<void>;
    updateEntry(id: bigint, groupName: string, groupUrl: string, datePosted: string, postContent: string, numReactions: bigint, numComments: bigint, responseStatus: ResponseStatus, followUpDate: string, craftCategory: CraftCategory, typeOfInterest: TypeOfInterest, eventType: EventType, leadContactInfo: string, attachment: ExternalBlob | null): Promise<FacebookOutreachEntry>;
}
import type { CraftCategory as _CraftCategory, EventType as _EventType, ExternalBlob as _ExternalBlob, FacebookOutreachEntry as _FacebookOutreachEntry, ResponseStatus as _ResponseStatus, TypeOfInterest as _TypeOfInterest, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEntry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: ResponseStatus, arg7: string, arg8: CraftCategory, arg9: TypeOfInterest, arg10: EventType, arg11: string, arg12: ExternalBlob | null): Promise<FacebookOutreachEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createEntry(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_ResponseStatus_n10(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_CraftCategory_n12(this._uploadFile, this._downloadFile, arg8), to_candid_TypeOfInterest_n14(this._uploadFile, this._downloadFile, arg9), to_candid_EventType_n16(this._uploadFile, this._downloadFile, arg10), arg11, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg12));
                return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEntry(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_ResponseStatus_n10(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_CraftCategory_n12(this._uploadFile, this._downloadFile, arg8), to_candid_TypeOfInterest_n14(this._uploadFile, this._downloadFile, arg9), to_candid_EventType_n16(this._uploadFile, this._downloadFile, arg10), arg11, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg12));
            return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntry(arg0: bigint): Promise<FacebookOutreachEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUpToday(arg0: string): Promise<Array<FacebookOutreachEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpToday(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpToday(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupNotes(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupNotes(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupNotes(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupResponseSummary(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupResponseSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupResponseSummary();
            return result;
        }
    }
    async getHookTemplatesForCaller(): Promise<Array<HookTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHookTemplatesForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHookTemplatesForCaller();
            return result;
        }
    }
    async getInquirySummaryByEventType(): Promise<InquirySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquirySummaryByEventType();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquirySummaryByEventType();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async health(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllGroupNotes(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllGroupNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllGroupNotes();
            return result;
        }
    }
    async listEntries(arg0: bigint, arg1: bigint): Promise<Array<FacebookOutreachEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEntries(arg0, arg1);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEntries(arg0, arg1);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveHookTemplates(arg0: Array<HookTemplate>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHookTemplates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHookTemplates(arg0);
            return result;
        }
    }
    async setGroupNotes(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGroupNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGroupNotes(arg0, arg1);
            return result;
        }
    }
    async updateEntry(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: ResponseStatus, arg8: string, arg9: CraftCategory, arg10: TypeOfInterest, arg11: EventType, arg12: string, arg13: ExternalBlob | null): Promise<FacebookOutreachEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_ResponseStatus_n10(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_CraftCategory_n12(this._uploadFile, this._downloadFile, arg9), to_candid_TypeOfInterest_n14(this._uploadFile, this._downloadFile, arg10), to_candid_EventType_n16(this._uploadFile, this._downloadFile, arg11), arg12, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg13));
                return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_ResponseStatus_n10(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_CraftCategory_n12(this._uploadFile, this._downloadFile, arg9), to_candid_TypeOfInterest_n14(this._uploadFile, this._downloadFile, arg10), to_candid_EventType_n16(this._uploadFile, this._downloadFile, arg11), arg12, await to_candid_opt_n18(this._uploadFile, this._downloadFile, arg13));
            return from_candid_FacebookOutreachEntry_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CraftCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CraftCategory): CraftCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FacebookOutreachEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FacebookOutreachEntry): Promise<FacebookOutreachEntry> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ResponseStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResponseStatus): ResponseStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TypeOfInterest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypeOfInterest): TypeOfInterest {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    typeOfInterest: _TypeOfInterest;
    owner: Principal;
    createdAt: bigint;
    postContent: string;
    responseStatus: _ResponseStatus;
    updatedAt: bigint;
    numReactions: bigint;
    datePosted: string;
    groupUrl: string;
    numComments: bigint;
    leadContactInfo: string;
    craftCategory: _CraftCategory;
    groupName: string;
    attachment: [] | [_ExternalBlob];
    followUpDate: string;
    eventType: _EventType;
}): Promise<{
    id: bigint;
    typeOfInterest: TypeOfInterest;
    owner: Principal;
    createdAt: bigint;
    postContent: string;
    responseStatus: ResponseStatus;
    updatedAt: bigint;
    numReactions: bigint;
    datePosted: string;
    groupUrl: string;
    numComments: bigint;
    leadContactInfo: string;
    craftCategory: CraftCategory;
    groupName: string;
    attachment?: ExternalBlob;
    followUpDate: string;
    eventType: EventType;
}> {
    return {
        id: value.id,
        typeOfInterest: from_candid_TypeOfInterest_n22(_uploadFile, _downloadFile, value.typeOfInterest),
        owner: value.owner,
        createdAt: value.createdAt,
        postContent: value.postContent,
        responseStatus: from_candid_ResponseStatus_n24(_uploadFile, _downloadFile, value.responseStatus),
        updatedAt: value.updatedAt,
        numReactions: value.numReactions,
        datePosted: value.datePosted,
        groupUrl: value.groupUrl,
        numComments: value.numComments,
        leadContactInfo: value.leadContactInfo,
        craftCategory: from_candid_CraftCategory_n26(_uploadFile, _downloadFile, value.craftCategory),
        groupName: value.groupName,
        attachment: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.attachment)),
        followUpDate: value.followUpDate,
        eventType: from_candid_EventType_n30(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Availability: null;
} | {
    Price: null;
} | {
    GroupBooking: null;
}): TypeOfInterest {
    return "Availability" in value ? TypeOfInterest.Availability : "Price" in value ? TypeOfInterest.Price : "GroupBooking" in value ? TypeOfInterest.GroupBooking : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LeadsGenerated: null;
} | {
    NoResponse: null;
} | {
    ActiveDiscussion: null;
} | {
    NegativeFeedback: null;
}): ResponseStatus {
    return "LeadsGenerated" in value ? ResponseStatus.LeadsGenerated : "NoResponse" in value ? ResponseStatus.NoResponse : "ActiveDiscussion" in value ? ResponseStatus.ActiveDiscussion : "NegativeFeedback" in value ? ResponseStatus.NegativeFeedback : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CandleMaking: null;
} | {
    SoapMaking: null;
} | {
    SplatterRoom: null;
}): CraftCategory {
    return "CandleMaking" in value ? CraftCategory.CandleMaking : "SoapMaking" in value ? CraftCategory.SoapMaking : "SplatterRoom" in value ? CraftCategory.SplatterRoom : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GeneralDIYIndividual: null;
} | {
    BirthdayPartyKids: null;
} | {
    BirthdayPartyAdult: null;
} | {
    BacheloretteBridalShower: null;
} | {
    GirlsNightOut: null;
} | {
    CorporateTeamBuilding: null;
} | {
    FieldTrips: null;
}): EventType {
    return "GeneralDIYIndividual" in value ? EventType.GeneralDIYIndividual : "BirthdayPartyKids" in value ? EventType.BirthdayPartyKids : "BirthdayPartyAdult" in value ? EventType.BirthdayPartyAdult : "BacheloretteBridalShower" in value ? EventType.BacheloretteBridalShower : "GirlsNightOut" in value ? EventType.GirlsNightOut : "CorporateTeamBuilding" in value ? EventType.CorporateTeamBuilding : "FieldTrips" in value ? EventType.FieldTrips : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FacebookOutreachEntry>): Promise<Array<FacebookOutreachEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FacebookOutreachEntry_n20(_uploadFile, _downloadFile, x)));
}
function to_candid_CraftCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CraftCategory): _CraftCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ResponseStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResponseStatus): _ResponseStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TypeOfInterest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TypeOfInterest): _TypeOfInterest {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResponseStatus): {
    LeadsGenerated: null;
} | {
    NoResponse: null;
} | {
    ActiveDiscussion: null;
} | {
    NegativeFeedback: null;
} {
    return value == ResponseStatus.LeadsGenerated ? {
        LeadsGenerated: null
    } : value == ResponseStatus.NoResponse ? {
        NoResponse: null
    } : value == ResponseStatus.ActiveDiscussion ? {
        ActiveDiscussion: null
    } : value == ResponseStatus.NegativeFeedback ? {
        NegativeFeedback: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CraftCategory): {
    CandleMaking: null;
} | {
    SoapMaking: null;
} | {
    SplatterRoom: null;
} {
    return value == CraftCategory.CandleMaking ? {
        CandleMaking: null
    } : value == CraftCategory.SoapMaking ? {
        SoapMaking: null
    } : value == CraftCategory.SplatterRoom ? {
        SplatterRoom: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TypeOfInterest): {
    Availability: null;
} | {
    Price: null;
} | {
    GroupBooking: null;
} {
    return value == TypeOfInterest.Availability ? {
        Availability: null
    } : value == TypeOfInterest.Price ? {
        Price: null
    } : value == TypeOfInterest.GroupBooking ? {
        GroupBooking: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    GeneralDIYIndividual: null;
} | {
    BirthdayPartyKids: null;
} | {
    BirthdayPartyAdult: null;
} | {
    BacheloretteBridalShower: null;
} | {
    GirlsNightOut: null;
} | {
    CorporateTeamBuilding: null;
} | {
    FieldTrips: null;
} {
    return value == EventType.GeneralDIYIndividual ? {
        GeneralDIYIndividual: null
    } : value == EventType.BirthdayPartyKids ? {
        BirthdayPartyKids: null
    } : value == EventType.BirthdayPartyAdult ? {
        BirthdayPartyAdult: null
    } : value == EventType.BacheloretteBridalShower ? {
        BacheloretteBridalShower: null
    } : value == EventType.GirlsNightOut ? {
        GirlsNightOut: null
    } : value == EventType.CorporateTeamBuilding ? {
        CorporateTeamBuilding: null
    } : value == EventType.FieldTrips ? {
        FieldTrips: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
